spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/mytiendita
spring.datasource.username=mytiendita_admin
spring.datasource.password=password_mytiendita
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.hikari.connection-timeout=5000
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=1800000
spring.jpa.properties.hibernate.jdbc.time_zone=America/Bogota

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

server.address=0.0.0.0
server.port=8080